### ISSUE TITLE
Little case in README.md

### ISSUE THREAD

**Issue by xchern** [njzhangyifei/msys2-mingw-shortcut-menus#2]
"git clone" through ssh needs ssh permission
`git clone git@github.com:njzhangyifei/msys2-mingw-shortcut-menus.git`

and it will work well cloning via https
`git clone https://github.com/njzhangyifei/msys2-mingw-shortcut-menus.git`

**Comment by njzhangyifei** [comment]
Added a tip in README.md with commit 57ee6770487f68ebbf1a3c61e48dbfce61f3cd50
