### ISSUE TITLE
the script is not worked after update the msys2

### ISSUE THREAD

**Issue by ghost** [njzhangyifei/msys2-mingw-shortcut-menus#3]
Today after the "pacman -Syu"
the mingw64_shell.bat content is changed:

```
:
@echo off

rem To activate windows native symlinks uncomment next line
rem set MSYS=winsymlinks:nativestrict

rem Set debugging program for errors
rem set MSYS=error_start:%WD%../../mingw64/bin/qtcreator.exe^|-debug^|^<process-id^>

rem To export full current PATH from environment into MSYS2 uncomment next line
rem set SET_FULL_PATH=1

call "%~dp0start_shell.cmd" -mingw64 %*
:EOF
```

it seems it call the script "start_shell.cmd" instead and old script is not workded anymore.

Thanks for fixing this issue! :)

**Comment by njzhangyifei** [comment]
I haven't upgraded my msys2 yet. Will look into this.

**Comment by njzhangyifei** [comment]
fixed with 86a62dd91cc9a7850da6c54bacd0aef0ae702880, have a try.

**Comment by ghost** [comment]
@njzhangyifei It works! thank you guy~

**Comment by ghost** [comment]
Well, after update again, the script is not work again...
It need change `msys2_shell.cmd -mingw64 -here \"%v\"`
to `msys2_shell.cmd -mingw64 -where \"%v\"`

**Comment by njzhangyifei** [comment]
@Neroldy the script should be up-to-date, could you give it a try?

**Comment by ghost** [comment]
@njzhangyifei The script works fine, thanks~
