### ISSUE TITLE
make doc more clear

### ISSUE THREAD

**Issue by eromoe** [njzhangyifei/msys2-mingw-shortcut-menus#4]
usage step 3:
`./install and follow the instructions`
You should say use what shell. 

`cmd` can not excute `./install`.
And I have installed `git-bash`, the easiest way is use right click menu `git-bash(embed mingw64)` to execute `./install`.
But I afraid this would add another `git-bash(embed mingw64)`. 
I'd like use another independent `mingw64`(I install another one) because `git-bash`'s`mingw64` is less function.

But I don't know how to do,
`mingw64(I intalled )`  do not have a exe like `cmd.exe`, I can't figure out how to use `mingw64(I intalled )` to excute `./install`

**Comment by njzhangyifei** [comment]
I guess you will need to install MSYS/MSYS2. See http://www.mingw.org/wiki/msys and https://msys2.github.io/. 

You need a unix shell program (preferably bash) to run the script.
