### ISSUE TITLE
filesystem 2016.05-2 breaking functionality

### ISSUE THREAD

**Issue by pfruh** [njzhangyifei/msys2-mingw-shortcut-menus#7]
The new 2016.05-2 update of filesystem breaks the functionality, since all start scripts got unified:

> WARNING: the shell starting scripts have been unified. Please update your
> shortcuts to the following targets, otherwise they will STOP WORKING:
> - MSYS2_ROOT\msys2_shell.cmd -mingw32
> - MSYS2_ROOT\msys2_shell.cmd -mingw64
> - MSYS2_ROOT\msys2_shell.cmd -msys

however just replacing the scripts in the code with the new script and the argument doesn't seem to work, I guess the new script handles the arguments differently.

**Comment by njzhangyifei** [comment]
Thank you for open this issue. I will look into this issue these two days.

**Comment by njzhangyifei** [comment]
@Kaeltis Any ideas on how to determine the version (before/after this update)?

**Comment by njzhangyifei** [comment]
Nvm, I've done the changes. Fixed with commit 5d08c9e

Please try install this again. With this update, the need for separate `.bat` file for invoking the shell is no longer required. The install script now only generates a single `.reg` file

Friendly ping @Neroldy

**Comment by ghost** [comment]
@njzhangyifei 
Good Job!

**Comment by pfruh** [comment]
Nice @njzhangyifei , seems to be working now :+1: 

One little thing - theres to many slashes in the .reg file now, should only be 2 slashes instead of 4 :D

`C:\\msys64\\\\msys2_shell.cmd`

**Comment by njzhangyifei** [comment]
Fixed with 8d87052f5334dfdb63476f2d1e0a894eec655f56. Closing this.
